export const SAVE_PHOTO_REQUEST = 'SAVE_PHOTO_REQUEST';
export const DELETE_PHOTO_REQUEST = 'DELETE_PHOTO_REQUEST';
export const UPDATE_PHOTO_REQUEST = 'UPDATE_PHOTO_REQUEST';
export const GET_PHOTO_REQUEST = 'GET_PHOTO_REQUEST';
export const PHOTO_SUCCESS = 'PHOTO_SUCCESS';
export const PHOTO_FAILURE = 'PHOTO_FAILURE';